#index:
#    path: /
#    controller: App\Controller\DefaultController::index
booking_show:
    path: /booking/{id}
    controller: App\Controller\BookingLController::showb
    requirements:
    methods: GET
    
