#index:
#    path: /
#    controller: App\Controller\DefaultController::index
reclamation_index:
  path: /reclamations/index
  controller: App\Controller\ReclamationController::index
note_index:
  path: /notes/index
  controller: App\Controller\NoteController::index
repondre_reclamation:
  path: /repondre-reclamation/{reclamationId}
  controller: App\Controller\ReponseController::repondreReclamation
